name: multi_vendor
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  image_picker: ^0.8.5+3
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  firebase_storage: ^10.3.1
  image_picker_web: ^2.1.1
  uuid: ^3.0.6
  staggered_grid_view_flutter: ^0.0.4
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  badges: ^2.0.3
  sn_progress_dialog: ^1.0.8
  flutter_datetime_picker: ^1.5.1
  file_picker: ^5.0.0
  flutter_stripe: ^4.0.0
  http: ^0.13.4
  flutter_rating_bar: ^4.0.1
  expandable: ^5.0.1
  country_state_city_picker: ^1.2.8
  flutter_pw_validator: ^1.4.2
  google_sign_in: ^5.4.1
  lottie: ^1.4.1
  gradient_borders: ^0.2.0
  shared_preferences: ^2.0.15
  dotted_border: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/
    - images/men/
    - images/try/
    - images/inapp/
    - images/women/
    - images/shoes/
    - images/electronics/
    - images/beauty/
    - images/kids/
    - images/homegarden/
    - images/accessories/
    - images/bags/
    - images/on_board/
  fonts:
   - family: Acme
     fonts:
      - asset: fonts/Acme-Regular.ttf
