// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API key',
    appId: 'app id',
    messagingSenderId: 'msg sender id',
    projectId: 'project id',
    authDomain: 'auth domain',
    storageBucket: 'Storage bucket',
    measurementId: 'measurementId',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API key',
    appId: 'app id',
    messagingSenderId: 'msg sender id',
    projectId: 'project id',
    storageBucket: 'Storage bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API key',
    appId: 'app id',
    messagingSenderId: 'msg sender id',
    projectId: 'project id',
    storageBucket: 'Storage bucket',
    iosClientId: 'ios client id',
    iosBundleId: 'ios bundle id',
  );
}
